import json

markdown_content = """# Sephora Executive Terminal — Speaker Script
### 14 Slides • 10 Minutes • ~40 seconds per slide
### Rule: Speak like a C-level executive to a Board of Directors. Short sentences. High impact. Lead with the 'So What.'

---

## Slide 01 — Provocation (Which Brand Next?)
**⏱ 40 seconds**

> Sephora asked us one question: **can you predict which brand a customer will buy next — even if they've never bought it before?**
>
> We are not doing this as an academic exercise. We are doing this to solve three commercial objectives: to drive average basket size up, to engineer brand discovery, and to power the entire recommendation architecture across the app, CRM, and in-store.
>
> Here is the baseline fact: when a customer discovers just one new brand through this system, their basket size increases from €72 to €84. That's a 15.8% lift. 

---

## Slide 02 — The Winning Formula (Success Definition)
**⏱ 40 seconds**

> If we are going to build a recommendation engine, we must define what a 'good' recommendation is.
>
> We defined success using a weighted commercial score: 40% based on basket size lift, 30% on increasing brand diversity, and 30% on driving repeat purchase frequency. 
>
> Against this rubric, we tested three scenarios. The 'Balanced' scenario won with a 3.27% conversion rate. This proved that pure profit-chasing fails, and pure novelty-seeking fails. To maximize revenue, the algorithm must weigh high margin equally with new discovery.

---

## Slide 03 — Command of the Dataset
**⏱ 40 seconds**

> A model is only as good as its data integrity. Here is our command of the dataset.
>
> We processed 385,879 clean transaction rows across 50,805 loyalty customers and 239 brands.
>
> We split the data by time: January through September is our training window. October through December is our holdout validation window. There is zero data leakage. If a recommendation works in this presentation, it means it genuinely predicted a future purchase.

---

## Slide 04 — The Explorer Effect
**⏱ 40 seconds**

> This is our most significant behavioral finding. 
>
> You might assume a recommendation system is best used on your most loyal customers. The math disagrees. The model works exponentially better on “Explorers” — customers mathematically proven to be open to trying new things.
>
> The business application is simple: do not waste recommendation real estate on a customer who only buys Chanel. Deploy the algorithm on Explorers. That is where we capture the incremental €11.49 per basket.

---

## Slide 05 — The Top 11 Pairs (The Deliverable)
**⏱ 40 seconds**

> Let's look at the actual output. This is the primary deliverable generated by the engine.
>
> From thousands of interactions, these are the 11 highest-confidence brand pairs in Sephora France. The top pair — HOURGLASS and WESTMAN ATELIER — has a 44.4x lift. This means a customer is 44 times more likely to buy both together than by random chance.
>
> Look down to number three: ILIA and KOSAS at 13.7x lift. These 11 pairs are mathematically validated and completely clean of business guardrail violations. They are ready to be deployed.

---

## Slide 06 — The Action Playbook
**⏱ 40 seconds**

> High-confidence pairs mean nothing without an activation strategy. Here is the operational playbook.
>
> **In-Store**: We mandate physical cross-merchandising. HOURGLASS and WESTMAN ATELIER must sit side-by-side on premium endcaps. 
>
> **CRM & Email**: We use "Rebound" journeys. If someone buys PAT MC GRATH, exactly 48 hours later, we trigger a dedicated email for PAULA'S CHOICE. 
>
> **App & Digital**: For the DRUNK ELEPHANT to LANEIGE pipeline, we inject these pairs directly into the "You Would Also Love" checkout carousel. We convert correlation into immediate revenue.

---

## Slide 07 — The Proof Engine
**⏱ 40 seconds**

> You should not trust a black-box algorithm. Here is our integrity funnel.
>
> We started with 8,357 raw brand combinations. We challenged them fiercely. We removed 4,359 pairs for statistical instability. We deleted 179 trivial pairs owned by the same parent companies. We ran permutation tests to ensure the probability wasn't just random luck.
>
> The result: 203 absolute "Gold Standard" pairs. You can take any one of these 203 pairs to the floor tomorrow with complete confidence.

---

## Slide 08 — 894 Behavioral Rules
**⏱ 40 seconds**

> The engine does more than pair brands; it models human transitions.
>
> We mapped 224,212 chronological purchase sequences and generated 894 specific behavioral rules. We know exactly what happens when a Gen Z woman buys Huda Beauty (she stays in makeup 71% of the time, expecting to spend €30). 
>
> When we sorted these 894 rules by ROI, two distinct growth engines emerged. The next step was mapping these statistical rules to the humans driving them.

---

## Slide 09 — Persona: Gen Z Discovery Engine
**⏱ 40 seconds**

> The first growth engine is Generation Z. We call them the 'Discovery Engine.'
>
> We identified 1,425 high-frequency Gen Z buyers. They are make-up led, and they already favor premium exclusive brands. They possess the highest 'Explorer Index' of any demographic.
>
> The strategic action: This is our acquisition target. When we want to introduce a new brand quickly, we push it to Gen Z through the App and CRM channels where they have a 91% engagement rate. 

---

## Slide 10 — Persona: Boomers Loyalty Fortress
**⏱ 40 seconds**

> The second engine is the exact opposite. Baby Boomers. The 'Loyalty Fortress.'
>
> We identified 465 high-frequency Boomers. They are Fragrance-led, favoring heritage selective brands like Dior, Guerlain, and Chanel. They have the lowest willingness to explore, but they have the highest average basket size at €46.
>
> The strategic action: Protection. We do not bombard them with new trends. We optimize their recurring fragrance purchases and carefully protect the luxury relationship.

---

## Slide 11 — The Cost of Being Wrong (LTV Protection)
**⏱ 40 seconds**

> This brings us to a fundamental board-level risk: the cost of being wrong. 
>
> A raw machine learning model will look at overall popularity and recommend trendy teen haircare—like Olaplex or Briogeo—to our high-net-worth Boomers. That generation mismatch destroys the luxury experience and causes churn.
>
> We built an Integrity Shield. It actively suppressed 6,995 of these toxic recommendations. By stopping the algorithm from making bad suggestions, we protected €491,476 in Boomer Lifetime Value. A good system drives sales; a great system protects equity.

---

## Slide 12 — Strategy I: The Acquisition Engine
**⏱ 40 seconds**

> To wrap up, here are our two strategic recommendations for immediate rollout. First, the Acquisition Engine.
>
> We will deploy the 217 validated pairs to regional store directors to force physical cross-merchandising. 
>
> We will target the 'Untapped Explorers'—specifically 16,000 Gen Z customers with high exploratory patterns who have never bought Drunk Elephant. They are mathematically our cheapest conversions. And finally, we will automate cross-sell e-mails tied specifically to Sephora Collection purchases, which we identified as the universal rebound brand.

---

## Slide 13 — Strategy II: The Protection Engine
**⏱ 40 seconds**

> Second, the Protection Engine. 
>
> We will immediately upload the 'Do-Not-Recommend' suppression list to the CRM. We must permanently block those 14 toxic trend brands from reaching our heritage buyers, locking down that €491,000 in VIP revenue.
>
> From there, we launch strict A/B testing. The treatment group gets our recommendation engine; the control gets standard merchandising. We will halt the test instantly if churn increases by even 0.5%.

---

## Slide 14 — The Final Verdict
**⏱ 40 seconds**

> This is the final verdict. 
>
> In Slide 2, we promised to hit a target of +€10.00 incremental lift per visit without diluting margins. 
>
> The actual delivery across our Q4 validation dataset: The engine triggered 659 cross-brand conversions. We achieved an actual incremental AOV lift of +€11.49 per discovery. And we shielded nearly half a million euros in baseline loyalty revenue from algorithmic errors.
>
> At the scale of 80 million Sephora loyalty members, this is not a marginal optimization. This is a primary driver of enterprise value. 
>
> Thank you. I welcome your questions.
"""

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [line + "\n" for line in markdown_content.split('\n')]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open("speaker.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
